plugins:
  - name: hello-world
    id: hello-world
    uses:
      - plugin: http://127.0.0.1:9090
        with:
          # Define configurable items here and the kernel will pass these to the plugin.
          configurableResponse: "Hello, is it me you are looking for?"
          customStringsUrl: "https://raw.githubusercontent.com/ubiquibot/plugin-template/development/strings.json"
